name: beatrivals_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+22

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- CORE PACKAGES ---
  flutter_riverpod: ^2.5.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.1
  
  # Utility
  rxdart: ^0.27.7 
  async: ^2.11.0       
  timeago: ^3.6.1 
  cupertino_icons: ^1.0.6 
  
  # Web Standard
  share_plus: ^10.0.0
  
  image_picker: ^1.1.1
  uuid: ^4.4.0

  # Other Features
  flutter_stripe: ^10.1.1
  
  # Video Recording & Playback
  camera: ^0.10.5+9
  path_provider: ^2.1.3
  video_player: ^2.8.6
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true